name: roxs-voting-app

services:
  vote:
    container_name: vote
    build: ./app/vote
    image: johndevsigner/roxs-voting-app-vote
    env_file:
      - ./.env
      - ./app/vote/.env.local
    networks:
      - voting_app_network
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  result:
    container_name: result
    build: ./app/result
    image: johndevsigner/roxs-voting-app-result
    env_file:
      - ./.env
    networks:
      - voting_app_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    container_name: worker
    build: ./app/worker
    image: johndevsigner/roxs-voting-app-worker
    env_file:
      - ./.env
    networks:
      - voting_app_network
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  redis:
    container_name: redis_cache
    image: redis:7.2-alpine
    networks:
      - voting_app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    env_file:
      - ./postgres.env
    environment:
      PGUSER: ${POSTGRES_USER:-postgres}
      PGDATABASE: ${POSTGRES_DB:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - voting_app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

networks:
  voting_app_network:
    driver: bridge

volumes:
  db-data:
